
jwt.secretKey=QtE1AQ+Sg4pQ3MO1h+qXpOrqBhG9Cbwm8grihDObpoo=
jwt.expiration=86400000
jwt.refresh.expiration=604800000

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.ebanking=DEBUG

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.web.bind=DEBUG
logging.level.org.springframework.http.converter=DEBUG

twilio.accountSid=REDACTED_ACCOUNT_SID
twilio.authToken=REDACTED_AUTH_TOKEN
twilio.verify.serviceSid=REDACTED_SERVICE_SZA


admin.email=admin@ebank.com
admin.password=admin123


agent.email=agent@ebank.com
agent.password=agent123