
jwt.secretKey=QtE1AQ+Sg4pQ3MO1h+qXpOrqBhG9Cbwm8grihDObpoo=
jwt.expiration=86400000
jwt.refresh.expiration=604800000

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.ebanking=DEBUG

# Clé API fictive
infobip.api.key=App abcdef1234567890fakeapikey0987654321

# URL de base fictive (Infobip sandbox ou dummy)
infobip.base.url=https://api.infobip.fake.com

# Nom de l?expéditeur fictif (11 caractères max, lettres/chiffres sans espace)
infobip.sender=MyBankApp

twilio.verify.serviceSid=VAxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
twilio.accountSid=ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
twilio.authToken=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
twilio.fromPhone=+1415xxxxxxx

admin.email=admin@ebank.com
admin.password=admin123


agent.email=agent@ebank.com
agent.password=agent123