
jwt.secretKey=QtE1AQ+Sg4pQ3MO1h+qXpOrqBhG9Cbwm8grihDObpoo=
jwt.expiration=86400000
jwt.refresh.expiration=604800000

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.ebanking=DEBUG

infobip.api.key=App afb3037d9d37a3d34d9050ffddc7eab0-acbda8d1-4cf0-4739-92d0-e2e8d603132e
infobip.base.url=https://wgezr8.api.infobip.com
infobip.sender=e-banking

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


admin.email=admin@ebank.com
admin.password=admin123


agent.email=agent@ebank.com
agent.password=agent123